### ISSUE TITLE
velocity_x Flutter 3.7 호환성 이슈

### ISSUE THREAD

**Issue by yutae** [BansookNam/fast_app_base#1]
## velocity_x Flutter 3.7 호환성 이슈

참고 
https://github.com/iampawan/VelocityX/pull/174

**Comment by BansookNam** [comment]
아 이제 확인했네요.
아직 공식 배포는 없었지만, 곧 4.0.x가 배포된다고 합니다.

우선 아래의 디펜던시로 맞춰서 올리도록 할게요. 공유 감사합니다!
      url: 'https://github.com/iampawan/VelocityX.git'
      ref: 'e4059fc'
